version: "3"
networks:
  default:
    driver: bridge
services:
  tgi-service:
    image: ghcr.io/huggingface/tgi-gaudi:2.0.0
    container_name: tgi-gaudi-server
    ports:
      - "8008:80"
    volumes:
      - "./data:/data"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HF_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
    runtime: habana
    cap_add:
      - SYS_NICE
    ipc: host
    command: --model-id mistralai/Mistral-7B-Instruct-v0.3 --max-input-tokens 1024 --max-total-tokens 2048
  supervisor_agent:
    image: opea/comps-agent-langchain:latest
    container_name: supervisor-agent
    ports:
      - 9090:9090
    volumes:
      - ./tools/:/home/user/tools/
    environment:
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - port=9090
      - strategy=react
      - llm_endpoint_url=http://${host_ip}:8008
      - llm_engine=tgi
      - recursive_limit=5
      - tools=/home/user/tools/custom_tools.yaml